### ISSUE TITLE
OnChange, objects are empty

### ISSUE THREAD

**Issue by apapatp** [bergben/ng2-file-input#1]
First of all, awesome package and thanks for putting it out there. I installed the package and tested it in the html and the previews work fine and also setting multiple to true or false. However, when I console log the event with (onChange)="method($event)"

This is what I get:

```
{
    "currentFiles": [
        {}
    ],
    "action": "added",
    "file": {}
} {}
```

As you can see, everything is empty.

This is my app.module.ts file
```
import { Ng2FileInputModule } from 'ng2-file-input';
imports: [Ng2FileInputModule.forRoot()]
```

My component html file:
	`<ng2-file-input (onChange)="fileChange($event)" placeholder="Profile Picture" [drop-text]="'my very custom dropzone text'" [multiple]="false"></ng2-file-input>`

My component.ts file:
```
fileChange(event: any){
    console.log(`This is file ${JSON.stringify(event, null, 4)} ${JSON.stringify(event.file, null, 4)}`);
}
```

I searched for the files in node_module folder and i was able to see.

```
Ng2FileInputComponent.prototype.handleFile = function (file) {
        if (this.isValidFile(file)) {
            if (!this.multiple) {
                this.currentFiles = [];
            }
            this.currentFiles.push(file);
            console.log('This is current file ', this.currentFiles, ' and this is file ', file);
            this.output.emit({
                currentFiles: this.currentFiles,
                action: "added",
                file: file
            });
        }
    };
```

I changed the `file:file` to `file:"hi"` and that displayed in my fileChange($event) method in the component.ts file. Also, as you can see from above, I also have a console log that I put:

`console.log('This is current file ', this.currentFiles, ' and this is file ', file);
`
which prints:

```
lastModified: 1476747913000
lastModifiedDate: Mon Oct 17 2016 19:45:13 GMT-0400 (EDT)
name:"f6fdde3a-056a-4d08-bf53-a6c9aa289d28.png"
size:5272
type:"image/png"
webkitRelativePath:""
```

Now I really don't know why the object files are empty in the fileChange() method, maybe there is some sort of delay that I need to be looking for? I am using ng2-bootstrap and also have bootstrap cdn css. Please can you help with this?

**Comment by bergben** [comment]
Hey there @apapatp 
I have created a plunker for your described problem: https://plnkr.co/edit/JURNQyIS3r22NaYhAyAN

The problem is with the logging that you are doing. You can't stringify a file: http://stackoverflow.com/questions/15399248/javascript-can-you-serialize-a-file-object

At the plunker you can see how the logging should be done. 

Hope this helps you!

**Comment by apapatp** [comment]
@bergben thanks so much that helped. Appreciate it!

**Comment by Megamind2301** [comment]
@bergben How do i send image file to server i.e get that file object in POST data object? Since ngModel doesn't work.

**Comment by bergben** [comment]
@Megamind2301 
Since you get the currentFiles in the `onChange` event just assign them to a variable like
```
public fileChange(event: any){
    this.currentFiles=event.currentFiles;
}
```

To post them to the server please refer to the following SO:
https://stackoverflow.com/questions/32423348/angular2-post-uploaded-file
https://stackoverflow.com/questions/40214772/file-upload-in-angular-2

Hope this helps.

**Comment by Megamind2301** [comment]
is there a way i can limit image file size? @bergben

**Comment by bergben** [comment]
@Megamind2301 
There is no such option. You can however easily implement that yourself, since you have the file you'll get the size in MB like so:
`let currentSize = file.size / 1024 / 1024;`
And wrap a if statement around your `this.currentFiles=event.currentFiles` according to your wished max file size.
