### ISSUE TITLE
Show file content in text area

### ISSUE THREAD

**Issue by ketimaBU** [bergben/ng2-file-input#5]
Hi it is not an issue i m havin a struggle 
I am trying to load a file using ng2-file-input using following line :
`    <ng2-file-input (onChange)="onFileChange($event)"></ng2-file-input> 
`and in the component i am using :
```
public onFileChange(event: any)
   {
 console.log("the file has changed:", event);   
 console.log('This is file' + JSON.stringify(event, null, 4)+JSON.stringify(event.file, null, 4));
    }
```

I want to know if there is any way to get the file content so i can show it in text area

**Comment by bergben** [comment]
Hey there,

assuming that the user can only select .txt, .json etc. files, in order to show the contents of a file in a text area you'll have to read the contents of a file somehow like this: https://stackoverflow.com/questions/750032/reading-file-contents-on-the-client-side-in-javascript-in-various-browsers
