### ISSUE TITLE
fully qualified path in event

### ISSUE THREAD

**Issue by scottellis64** [bergben/ng2-file-input#9]
I'm not seeing the full path in the file-added event.  Am I able to get to the file content once the file is selected, or the full path of the file selected?

**Comment by bergben** [comment]
Hi @scottellis64,
if you mean the full path to the file that the user has selected then the answer is no, you won't be able to get the full path because of JavaScript security restrictions... Please refer to [this question on SO](https://stackoverflow.com/questions/15201071/how-to-get-full-path-of-selected-file-on-change-of-input-type-file-using-jav)

**Comment by scottellis64** [comment]
Thanks, I was just about to retract the question because I figured out how to acquire the content of the file through the FileReader API.  Thanks!
